"""Make event_request.purpose required

Revision ID: dc3a1e9731e0
Revises: ee2ce3d87fb9
Create Date: 2026-01-21 00:08:28.572406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc3a1e9731e0'
down_revision = 'ee2ce3d87fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_requests', schema=None) as batch_op:
        batch_op.alter_column('purpose',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_requests', schema=None) as batch_op:
        batch_op.alter_column('purpose',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
